# Creates a Drupal web app with MySQL database
# Usage: docker-compose up -d
version: '2'
services:
  drupal:
    image: drupal:8.1.2-apache
    container_name: drupal_8081
    volumes:
      - /var/www/html
      - ./scripts/php.ini:/usr/local/etc/php/php.ini
      - ./scripts:/scripts
      #- ./modules/:/var/www/html/modules
      #- ./themes/:/var/www/html/themes
      #- ./libraries/:/var/www/html/libraries
      #- ./profiles/:/var/www/html/profiles
      #- $(which drush):/usr/local/bin/drush
      #- $(which drupal):/usr/local/bin/drupal
    volumes_from:
      - drush_volumed
      - drupalconsole_volumed
    ports:
      - "8081:80"
      - "25"
    links:
      - mysql
      - phpmyadmin
      - mailhog
  mysql:
    image: mysql:5.5
    container_name: mysql
    hostname: localhost
    # volumes:
    #   - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_8090
    environment:
      - PMA_ARBITRARY=1
    ports:
      - '8090:80'
    links:
      - mysql
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_8025
    hostname: mailhog
    ports:
      - "8025:8025"
      - "1025"
  drush_volumed:
    build:
      context: ./builds/drush-volumed
      args:
        - DRUSH_VERSION=8.1.2
    image: drush-volumed:8.1.2
    container_name: drush_volumed
  drupalconsole_volumed:
    build:
      context: ./builds/drupalconsole-volumed
      args:
        - CONSOLE_VERSION=1.0.0-beta2
    image: drupalconsole-volumed:1.0.0-beta2
    container_name: drupalconsole_volumed
